[package]
name = "decode_gbk"
version = "0.1.0"
authors = ["planet0104 <planet0104@gmail.com>"]
edition = "2018"

[dependencies]
encoding_rs = "0.8.17"
byteorder = "1.3.2"
image = "*"
imageproc = "0.18.0"

[profile.release]
lto = true